In [ ]:
n = 3
state_tensor = np.zeros((2,)*n)
state_tensor[(0,)*n] = 1
print(state_tensor)
# OR
# state = np.zeros(2**n)
# state[0] = 1
# state_t = state.reshape((2,)*n)
# print(state_t)

[[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
# tensor state to normal state representation
state_array = state_tensor.flatten()
for index,val in enumerate(state_array):
    print((bin(index)[2:].zfill(n), int(val)))

('000', 0)
('001', 0)
('010', 0)
('011', 0)
('100', 0)
('101', 0)
('110', 1)
('111', 0)


In [ ]:
i = 0
state_tensor = np.tensordot(X, state_tensor, axes=(1, i)) 
state_tensor = np.moveaxis(state_tensor, 0, i)
print(state_tensor)

[[[0. 0.]
  [0. 0.]]

 [[1. 0.]
  [0. 0.]]]


In [ ]:
control = 0
target = 1

# Apply CX gate using tensordot on control and target qubits
state_tensor = np.tensordot(CX, state_tensor, axes=([2, 3], [control, target]))
# Move axes to retain the original shape (2, 2, ..., 2)
state_tensor = np.moveaxis(state_tensor, [0, 1], [control, target])
print(state_tensor)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 0.]]]


In [ ]:
# applying H gate on qubit 0
state_tensor = np.tensordot(H, state_tensor, axes=(1,0))
print(state_tensor)

[[[ 0.70710678  0.        ]
  [ 0.          0.        ]]

 [[-0.70710678  0.        ]
  [ 0.          0.        ]]]


In [ ]:
# Move the resulting axis to the first position to keep the shape consistent
state_tensor = np.moveaxis(state_tensor, 0, 0)
print(state_tensor)

[[[0.70710678 0.        ]
  [0.         0.        ]]

 [[0.70710678 0.        ]
  [0.         0.        ]]]


In [ ]:
# Rearrange axes to keep the shape consistent as (2, 2, 2)
state_tensor = np.moveaxis(state_tensor, [0, 1], [0, 1])
print(state_tensor)

[[[0.70710678 0.        ]
  [0.         0.        ]]

 [[0.         0.        ]
  [0.70710678 0.        ]]]
